Repository imfunniee/gitfolio, pull requests merged in 2019-05, with the labels that each got.

#8 Repo list now pulls from a JSON list like Blogs
  README.md
  assets/index.html
  build.js
  repos.js
  repos/repos.json
Labels: invalid

#30 Added sorting to repos and forks + support in build.js
  README.md
  assets/index.css
  assets/index.html
  assets/index.js
  build.js
  populate.js
Labels: enhancement

#25 Added A Suite of Improvements
  .gitignore
  README.md
  assets/blog/blog.json
  assets/blog/blogTemplate.html
  assets/themes/dark.css
  assets/themes/light.css
  blog.js
  blog/blog.json
  build.js
  config.json
  package-lock.json
  package.json
  populate.js
Labels: enhancement

#36 Dependabot JSDOM 15 -> 15.1
  package-lock.json
  package.json
Labels: package update

#45 fetch over 100 repos
  populate.js
Labels: enhancement

#29 Cli feature
  assets/index.html
  bin/gitfolio.js
  blog.js
  build.js
  default/blog.json
  default/config.json
  package.json
  populate.js
  update.js
  utils.js
Labels: enhancement

#47 + Service Worker
  assets/index.html
  assets/service-worker.js
  build.js
Labels: enhancement
